ASP/webgame/Controllers/DaXongController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanGame.Areas.Admin.Controllers
{
    public class DaXongController : Controller
    {
        //
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: /Admin/DaXong/
        public ActionResult Index(int ? page)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            int pagesize = 5;
            int pageNum = (page ?? 1);
            var nhanhang = from tt in data.DatHangs
                           where tt.DaGiao == true
                         && tt.HTGiaoHang == true
                       && tt.HTThanhToan == true
                           select tt;
            return View(nhanhang.ToPagedList(pageNum, pagesize));
        }
	}
}

ASP/webgame/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;
using PagedList;
using PagedList.Mvc;
namespace WebBanGame.Areas.Admin.Controllers
{
    public class GameController : Controller
    {
        //
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: /Admin/Game/
        [HttpGet]
        public ActionResult Them()
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            ViewBag.Masx = new SelectList(data.NhaSanXuats.ToList().OrderBy(n => n.TenNhaSanXuat), "MaNhaSanXuat", "TenNhaSanXuat");
            ViewBag.Maloai = new SelectList(data.LoaiGames.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");
            ViewBag.Mahm = new SelectList(data.HeMays.ToList().OrderBy(n => n.Tendong), "Madong", "Tendong");
            return View();
        }
        [HttpPost]
        public ActionResult Them(FormCollection collection, SanPham sp)
        {
            var CB_Name = collection["txttengame"];
            var CB_HangGame = int.Parse(collection["Masx"]);
            var CB_Theloai = int.Parse(collection["Maloai"]);
            var CB_anh = collection["txthinhanh"];
            var CB_motamh = collection["txtgioithieu"];
            var CB_video = collection["txtvideo"];
            var CB_Giaban = int.Parse(collection["txtgia"]);
            var CB_ngaycapnhat = DateTime.Parse(collection["txtngaydang"]);
            var CB_cauhinh = collection["txtcauhinh"];
            var CB_dongmay = int.Parse(collection["Mahm"]);
            var CB_hesokm = float.Parse(collection["txthskm"]);
            if (string.IsNullOrEmpty(CB_Name))
            {
                ViewData["Loi1"] = " Tên  không được để trống ";
            }
            else
            {
                sp.TenSP = CB_Name;
                sp.MaNhaSanXuat = CB_HangGame;
                sp.MaLoai = CB_Theloai;
                sp.HinhAnh = CB_anh;
                sp.MoTa = CB_motamh;
                if (collection["txttieubieu"] != null)
                    sp.TieuBieu = true;
                else
                    sp.TieuBieu = false;
                if (collection["txtkhuyemai"] != null)
                    sp.KhuyenMai = true;
                else
                    sp.KhuyenMai = false;
                sp.HesoKM = CB_hesokm;
                sp.Video = CB_video;
                sp.GiaBan = CB_Giaban;
                sp.NgayCapNhat = CB_ngaycapnhat;
                sp.CauHinh = CB_cauhinh;
                sp.Madong = CB_dongmay;
                data.SanPhams.InsertOnSubmit(sp);
                data.SubmitChanges();
                return RedirectToAction("Them");
            }
            return this.Them();
        }



    }
}

ASP/webgame/Controllers/KhoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanGame.Areas.Admin.Controllers
{
    public class KhoController : Controller
    {
        //
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: /Admin/Kho/
        public ActionResult Index(int ? page)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            int pagesize = 5;
            int pageNum = (page ?? 1);
            var giaohang = from tt in data.DatHangs
                           where tt.DaGiao == false
                            || tt.HTGiaoHang == false
                          || tt.HTThanhToan == false
                           select tt;
            return View(giaohang.ToPagedList(pageNum, pagesize));   
        }
        public ActionResult giaohang(int id, string strUrl)
        {
            var Egiao = data.DatHangs.First(m => m.SoDH == id);
            Egiao.DaGiao = true;
            UpdateModel(Egiao);
            data.SubmitChanges();
            return Redirect(strUrl);
        }
        public ActionResult thanhtoan(int id, string strUrl)
        {
            var Etoan = data.DatHangs.First(m => m.SoDH == id);
            Etoan.HTThanhToan = true;
            UpdateModel(Etoan);
            data.SubmitChanges();
            return Redirect(strUrl);
        }
        public ActionResult htgiaohang(int id, string strUrl)
        {
            var Ehang = data.DatHangs.First(m => m.SoDH == id);
            Ehang.HTGiaoHang = true;
            UpdateModel(Ehang);
            data.SubmitChanges();
            return Redirect(strUrl);
        }
        public ActionResult chinhsua(int id, string strUrl)
        {
            var Ehang = data.DatHangs.First(m => m.SoDH == id);
            Ehang.HTGiaoHang = false;
            Ehang.DaGiao = false;
            Ehang.HTThanhToan = false;
            UpdateModel(Ehang);
            data.SubmitChanges();
            return Redirect(strUrl);
        }
	}
}

ASP/webgame/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;

using PagedList;
using PagedList.Mvc;

namespace webgame.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        DataClasses1DataContext db = new DataClasses1DataContext();
        private List<SanPham> Laygamemoi(int count)
        {
            return db.SanPhams.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pagesize = 6;
            int pagenum = (page ?? 1);
            var gamemoi = Laygamemoi(12);
            return View(gamemoi.ToPagedList(pagenum,pagesize));
        }
        public ActionResult loaigame()
        {
            var loaigame = from lg in db.LoaiGames select lg;
            return PartialView(loaigame);
        }
        public ActionResult DongMay()
        {
            var hemay = from hm in db.HeMays select hm;
            return PartialView(hemay);
        }
       //tao kieu may tao PartViriew ma
        public ActionResult NhaSanXuat()
        {
            var nhasanxuat = from nsx in db.NhaSanXuats select nsx;
            return PartialView(nhasanxuat);
        }
        public ActionResult listspcungloai(int id)
        {
            var nhasanxuat = from nsx in db.SanPhams
                             where nsx.MaNhaSanXuat == id
                             select nsx;
            return PartialView(nhasanxuat);
        }
        public ActionResult listloaisp(int id)
        {
            var loai = from l in db.SanPhams
                             where l.MaLoai == id
                             select l;
            return PartialView(loai);
        }
        public ActionResult Dexuat()
        {
            var gamemoi = Laygamemoi(3);
            return PartialView(gamemoi);
        }
        public ActionResult listloaigame()
        {
            var hemay = from lg in db.HeMays select lg;
            return PartialView(hemay);
        }
        public ActionResult laysanphammoi(int id)
        {
            var nhasanxuat = from nsx in db.SanPhams
                             where nsx.MaLoai == id
                             select nsx;
            return PartialView(nhasanxuat);
        }

        public ActionResult chitiet(int id)
        {
            var chitiet = from ct in db.SanPhams
                          where ct.MaSP == id
                          select ct;
            return View(chitiet.Single());
        }
        public ActionResult Sptheodongmay(int id)
        {
            var dongmay = from dm in db.SanPhams
                          where dm.Madong == id
                          select dm;
            return View(dongmay);
        }
        public ActionResult Sptheonhasanxuat(int id)
        {
            var nhasanxuat = from nsx in db.SanPhams
                             where nsx.MaNhaSanXuat == id
                             select nsx;
            return View(nhasanxuat);
        }
        public ActionResult Sptheoloaigame(int id)
        {
            var loaigame = from lg in db.SanPhams
                           where lg.MaLoai == id
                           select lg;
            return View(loaigame);
        }
        public ActionResult Sptieubieu()
        {
            var gamemoi = Laygamemoi(12);
            return View(gamemoi);
        }
        public ActionResult Spkhuyenmai(int ? page)
        {
            int pagesize = 3;
            int pagenum = (page ?? 1);
            var gamemoi = Laygamemoi(6);
            return View(gamemoi.ToPagedList(pagenum, pagesize));
        }
        public ActionResult huongdanmuahang()
        {
            return View();
        }
        public ActionResult lienhe()
        {
            return View();
        }
    }
}

ASP/webgame/Views/Shared/LayoutAdmin.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Admin</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="~/assets/css/animate.min.css" rel="stylesheet" />
    <!--  Light Bootstrap Table core CSS    -->
    <link href="~/assets/css/light-bootstrap-dashboard.css" rel="stylesheet" />

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="~/assets/css/demo.css" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="~/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
   
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="purple" style="background-image:url("../../assets/img/sidebar-5.jpg")">
            <!--

                Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
                Tip 2: you can also add an image using data-image tag

            -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="@Url.Action("Index", "Admin")" class="simple-text">
                        Trang Admin
                    </a>
                </div>
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index", "Admin")">
                            <i class="pe-7s-graph"></i>
                            <p>Thống Kê</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Databse", "Database")">
                            <i class="pe-7s-note2"></i>
                            <p>DATABASE</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Them", "Game")">
                            <i class="pe-7s-news-paper"></i>
                            <p>GAME</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "LoaiGame")">
                            <i class="pe-7s-news-paper"></i>
                            <p>Loại Game</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "NhaCungCap")">
                            <i class="pe-7s-news-paper"></i>
                            <p>Nhà Cung Cấp</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "DongMay")">
                            <i class="pe-7s-news-paper"></i>
                            <p>Dòng Máy</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Map","Map")">
                            <i class="pe-7s-map-marker"></i>
                            <p>Bản Đồ Cửa Hàng</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Thongbao","Map")">
                            <i class="pe-7s-bell"></i>
                            <p>Thông Báo</p>
                        </a>
                    </li>
                    <li class="active-pro">
                        <a href="@Url.Action("Login", "Admin")">
                            <i class="pe-7s-rocket"></i>
                            <p>Exit</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Trang Chủ</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-dashboard"></i>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret"></b>
                                    <span class="notification">0</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Thông Báo</a></li>
                                    <li><a href="#">Góp Ý</a></li>
                                    <li><a href="#">Gmail</a></li>
                                    <li><a href="#">Facebook</a></li>
                                    <li><a href="#">FanPage</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="">
                                    <i class="fa fa-search"></i>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a>
                                    Xin Chào : Quan Dinh
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Danh Sách
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index", "KhachHang")">Khách Hàng</a></li>
                                    <li><a href="#">Kho</a></li>
                                    <li><a href="@Url.Action("Index", "HoaDon")">Hóa Đơn</a></li>
                                    <li><a href="@Url.Action("Databse", "Database")">GAME</a></li>
                                    <li><a href="#">Thống Kê Ngày</a></li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("Index", "Kho")">Quản Lý Đơn Đặt Hàng</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "KiemTraDonHang")">Kiểm Tra Đơn Hàng</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "DaXong")">Hàng đã giao</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="@Url.Action("Login", "Admin")">
                                    Đăng Xuất
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="content">
                @RenderBody()

            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="dashboard.html">
                                    Trang Chủ
                                </a>
                            </li>
                            <li>
                                <a href="https://www.facebook.com/Hutech-Shoes-1909218519350386/" target="_blank">
                                    FanPage: Hutech Shoes
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Cập Nhật
                                </a>
                            </li>
                            <li>
                                <a href="../index.html" target="_blank">
                                    Web: Trang Chủ Web
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy; 2017 <a href="">Quan Dinh Nguyen</a>
                    </p>
                </div>
            </footer>
        </div>
    </div>

</body>
<!--   Core JS Files   -->
<script src="~/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/assets/js/bootstrap.min.js" type="text/javascript"></script>
<!--  Checkbox, Radio & Switch Plugins -->
<script src="~/assets/js/bootstrap-checkbox-radio-switch.js"></script>
<!--  Charts Plugin -->
<script src="~/assets/js/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="vassets/js/bootstrap-notify.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="~/assets/js/light-bootstrap-dashboard.js"></script>
<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="~/assets/js/demo.js"></script>
<!-- <script type="text/javascript">
    $(document).ready(function(){

        demo.initChartist();

        $.notify({
            icon: 'pe-7s-gift',
            message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."

        },{
            type: 'info',
            timer: 4000
        });

    });
</script> -->
</html>