ASP/webgame/Controllers/KhachHangController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanGame.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        //
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: /Admin/KhachHang/
        public ActionResult Index(int? page)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            int pagenumber = (page ?? 1);
            int pagesize = 5;
            return View(data.KhachHangs.ToList().OrderBy(n => n.MaKhachHang).ToPagedList(pagenumber, pagesize));
        }
        public ActionResult Deletekh(int id)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            var D_kh = data.KhachHangs.First(m => m.MaKhachHang == id);
            return View(D_kh);
        }
        [HttpPost]
        public ActionResult Deletekh(int id, FormCollection collection)
        {

            var kh = data.KhachHangs.First(m => m.MaKhachHang == id);
            data.KhachHangs.DeleteOnSubmit(kh);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
	}
}

ASP/webgame/Views/KhachHang/Deletekh.cshtml
@{
    ViewBag.Title = "Deletekh";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Delete</h2>
<fieldset>
    <legend><font color=red>  Bạn có thật sư muốn xóa khách hàng!</font>    </legend>
    <div class="display-lable"> Mã Khách Hàng:@Model.MaKhachHang</div>
    <div class="display-lable"> Tên Khách Hàng  :@Model.TenKhachHang</div>
    <div class="display-lable"> Email  :@Model.Email</div>
    <div class="display-lable"> Số Điện Thoại  :@Model.SDT</div>
    <div class="display-lable"> Ngày Sinh  :@Model.NgaySinh</div>
    <div class="display-lable"> Địa Chỉ  :@Model.DiaChi</div>
    <div class="display-lable"> Tên Đăng Nhập :@Model.TenDangNhap</div>
    <div class="display-lable"> Tên Khách Hàng  :@Model.MatKhau</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <button type="submit" class="btn btn-danger">Xóa</button>
        <a href="@Url.Action("Index","KhachHang")" class="btn btn-primary">
            Trở Về
        </a>
    </p>
}

ASP/webgame/Views/KhachHang/Index.cshtml
@using webgame.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<KhachHang>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Bảng Thông Tin Khách Hàng</h4>
            <p class="category">Quản lý thông tin khách hàng</p>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover">
                <thead>
                <th>Mã Khách Hàng</th>
                <th>Tên Khách Hàng</th>
                <th>Email</th>
                <th>Số Điện Thoại</th>
                <th>Ngày Sinh</th>
                <th>Địa Chỉ</th>
                <th>Tên Đăng Nhập</th>
                <th>Mật Khẩu</th>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.MaKhachHang
                            </td>
                            <td>
                                @item.TenKhachHang
                            </td>
                            <td>
                                @item.Email
                            </td>
                            <td>
                                @item.SDT
                            </td>
                            <td>
                                @item.NgaySinh
                            </td>
                            <td>
                                @item.DiaChi
                            </td>
                            <td>
                                @item.TenDangNhap
                            </td>
                            <td>
                                @item.MatKhau
                            </td>
                            <td>
                                <a href="@Url.Action("Deletekh", new { id = item.MaKhachHang })">
                                    <img src="~/assets/img/icon_delete.png" width="20px" height="20px"> Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<footer class="footer">
    <div class="MenuTrang" style="text-align:center;">
        @Html.PagedListPager(Model, page => Url.Action
                    ("Index", new { page = page })) <br />
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>

</footer>