ASP/webgame/Controllers/DongMayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webgame.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanGame.Areas.Admin.Controllers
{
    public class DongMayController : Controller
    {
        //
        DataClasses1DataContext data = new DataClasses1DataContext();
        // GET: /Admin/DongMay/
        public ActionResult Index(int? page)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            int pagenumber = (page ?? 1);
            int pagesize = 5;
            return View(data.HeMays.ToList().OrderBy(n => n.Madong).ToPagedList(pagenumber, pagesize));
        }
        public ActionResult Them()
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Them(FormCollection collection, HeMay hm)
        {
            var CB_Name = collection["txttendongmay"];
            if (string.IsNullOrEmpty(CB_Name))
            {
                ViewData["Loi1"] = " Tên Dòng Máy không được để trống ";
            }
            else
            {
                hm.Tendong = CB_Name;
                data.HeMays.InsertOnSubmit(hm);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Them();
        }
        public ActionResult Editdm(int id)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            var E_dm = data.HeMays.First(m => m.Madong == id);
            return View(E_dm);
        }
        [HttpPost]
        public ActionResult Editdm(int id, FormCollection collection)
        {
            var CB_Name = collection["txttendong"];
            var Edm = data.HeMays.First(m => m.Madong == id);
            if (String.IsNullOrEmpty(CB_Name))
            {
                ViewData["Loi"] = "Tên không được để trống";
            }

            else
            {
                Edm.Tendong = CB_Name;
                UpdateModel(Edm);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Editdm(id);
        }
        public ActionResult Deletedm(int id)
        {
            if (Session["TenDangNhap"] == null || Session["TenDangNhap"].ToString() == "")
            {
                return RedirectToAction("Login", "Admin");
            }
            var D_dm = data.HeMays.First(m => m.Madong == id);
            return View(D_dm);
        }
        [HttpPost]
        public ActionResult Deletedm(int id, FormCollection collection)
        {

            var dmay = data.HeMays.First(m => m.Madong == id);
            data.HeMays.DeleteOnSubmit(dmay);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

	}
}

ASP/webgame/Views/DongMay/Deletedm.cshtml
@{
    ViewBag.Title = "Deletedm";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Delete</h2>
<fieldset>
    <legend><font color=red>  Bạn có thật sư muốn xóa!</font>    </legend>
    <div class="display-lable"> Mã Dòng:@Model.Madong</div>
    <div class="display-lable"> Tên Dòng  :@Model.Tendong</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <button type="submit" class="btn btn-danger">Xóa</button>
        <a href="@Url.Action("Index","DongMay")" class="btn btn-primary">
            Trở Về
        </a>
    </p>
}

ASP/webgame/Views/DongMay/Editdm.cshtml
@model webgame.Models.HeMay
@{
    ViewBag.Title = "Editdm";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-8">
        <div class="card">
            <div class="header">
                <h4 class="title">Sữa Dòng Máy</h4>
            </div>
            <div class="content">
                <form>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>ID (Mặc Định & Tự Tăng)</label>
                                <input type="text" class="form-control" disabled placeholder="@Model.Madong">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tên Dòng Máy</label>
                                <input type="text" class="form-control" name="txttendong" value="@Model.Tendong">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info btn-fill pull-right">Sữa Dòng Máy</button>
                    <button type="button" class="btn database"><a href="@Url.Action("Index", "DongMay")">Về Database</a></button>
                </form>
            </div>
        </div>
    </div>
}

ASP/webgame/Views/DongMay/Index.cshtml
@using webgame.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<HeMay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Bảng Thông Tin Dòng Máy</h4>
            <p class="category">Quản lý thông tin Dòng Máy</p>
            <br>
            <a href="@Url.Action("Them")">
                <input type="button" value="Thêm dòng máy" class="btn btn-default" />
            </a>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover">
                <thead>
                <th>Mã Dòng Máy</th>
                <th>Tên Dòng Máy</th>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Madong
                            </td>
                            <td>
                                @item.Tendong
                            </td>
                            <td>
                                <a href="@Url.Action("Editdm", new { id = item.Madong })">
                                    <img src="~/assets/img/icon_edit.png" width="20px" height="20px"> Edit
                                </a>
                            </td>
                            <td>
                                <a href="@Url.Action("Deletedm", new { id = item.Madong })">
                                    <img src="~/assets/img/icon_delete.png" width="20px" height="20px"> Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="MenuTrang" style="text-align:center;">
    @Html.PagedListPager(Model, page => Url.Action
                    ("Index", new { page = page })) <br />
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

<footer class="footer">
    

</footer>

ASP/webgame/Views/DongMay/Them.cshtml
@{
    ViewBag.Title = "Them";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="header">
                    <h4 class="title">Thêm Dòng Máy</h4>
                </div>
                <div class="content">
                    <form>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>ID (Mặc Định & Tự Tăng)</label>
                                    <input type="text" class="form-control" disabled placeholder="ID">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Tên Dòng Máy</label>
                                    <input type="text" class="form-control" name="txttendongmay">
                                    @ViewData["Loi1"]
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-info btn-fill pull-right">Thêm Dòng Máy</button>
                        <button type="button" class="btn database"><a href="@Url.Action("Index","DongMay")">Về Danh Sách Dòng Máy</a></button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="..." />
                </div>
                <div class="content">
                    <div class="author">
                        <a href="#">
                            <img class="avatar border-gray" src="~/assets/img/faces/index2.jpg" alt="..." />
                            <h4 class="title">
                                DucVM<br />
                                <small>(ProssVM)</small>
                            </h4>
                        </a>
                    </div>
                    <p class="description text-center">
                        "ProssVM <br>
                        Hãy sống cuộc đợi của bạn và <br>
                        đừng bao giờ gục ngã (Never Give Up)"
                    </p>
                </div>
                <hr>
                <div class="text-center">
                    <button href="https://www.facebook.com/duc.vm.7" target="_blank" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                    <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                    <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
}